GraphMetadata:
  max_vidg: 9
  min_vidg: 0
  num_border_vertices: 5
  num_edges: 5
  num_subgraphs: 2
  num_vertices: 10
  subgraphs:
  - gid: 0
    max_vidg: 4
    min_vidg: 0
    num_incoming_edges: 0
    num_outgoing_edges: 5
    num_vertices: 5
    vattr_id_to_file_path:
    - ../attributes/0/movie_vid.bin
    - ../attributes/0/movie_rating.bin
    - ../attributes/0/movie_year.bin
    - ../attributes/0/movie_genre.bin
    - ../attributes/0/movie_name.bin
    - ../attributes/0/movie_title.bin
    - ../attributes/0/movie_episode_name.bin
    - ../attributes/0/movie_episode_id.bin
    - ''
    - ''
    - ''
    - ''
    vattr_id_to_max_string_length:
    - 0
    - 0
    - 0
    - 6
    - 62
    - 33
    - 13
    - 5
    - 0
    - 0
    - 0
    - 0
    vattr_id_to_vattr_type:
    - uint32_t
    - uint8_t
    - uint16_t
    - string
    - string
    - string
    - string
    - string
    - uint32_t
    - string
    - uint32_t
    - string
    vattr_id_to_vlabel_id:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 2
    - 2
    vlabel_id_to_vidl_range:
    - - 0
      - 4
    - - 4294967295
      - 4294967295
    - - 4294967295
      - 4294967295
  - gid: 1
    max_vidg: 9
    min_vidg: 5
    num_incoming_edges: 5
    num_outgoing_edges: 0
    num_vertices: 5
    vattr_id_to_file_path:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ../attributes/1/cast_vid.bin
    - ../attributes/1/cast_name.bin
    - ../attributes/1/director_vid.bin
    - ../attributes/1/director_name.bin
    vattr_id_to_max_string_length:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 16
    - 0
    - 17
    vattr_id_to_vattr_type:
    - uint32_t
    - uint8_t
    - uint16_t
    - string
    - string
    - string
    - string
    - string
    - uint32_t
    - string
    - uint32_t
    - string
    vattr_id_to_vlabel_id:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 2
    - 2
    vlabel_id_to_vidl_range:
    - - 4294967295
      - 4294967295
    - - 0
      - 3
    - - 4
      - 4
  vlabel_id_to_vidl_range:
  - - 0
    - 4
  - - 5
    - 8
  - - 9
    - 9
