GraphMetadata:
  attr_id_to_attr_name:
    0: movie_vid
    1: movie_rating
    2: movie_year
    3: movie_genre
    4: movie_name
    5: movie_title
    6: movie_episode_name
    7: movie_episode_id
    8: movie_series_id
    9: cast_vid
    10: cast_name
    11: director_vid
    12: director_name
  label_id_to_label_name:
    0: Movie
    1: Cast
    2: Director
  max_global_vid: 9
  min_global_vid: 0
  num_border_vertices: 10
  num_edges: 10
  num_subgraphs: 2
  num_vertices: 10
  subgraphs:
  - gid: 0
    max_global_vid: 4
    min_global_vid: 0
    num_incoming_edges: 5
    num_outgoing_edges: 5
    num_vertices: 5
    vattr_id_to_file_path:
    - ../attributes/0/movie_vid.bin
    - ../attributes/0/movie_rating.bin
    - ../attributes/0/movie_year.bin
    - ../attributes/0/movie_genre.bin
    - ../attributes/0/movie_name.bin
    - ../attributes/0/movie_title.bin
    - ../attributes/0/movie_episode_name.bin
    - ../attributes/0/movie_episode_id.bin
    - ../attributes/0/movie_series_id.bin
    - ''
    - ''
    - ''
    - ''
    vattr_id_to_max_string_length:
    - 0
    - 0
    - 0
    - 9
    - 41
    - 34
    - 1
    - 5
    - 0
    - 0
    - 0
    - 0
    - 0
    vattr_id_to_vattr_type:
    - uint32_t
    - uint8_t
    - uint16_t
    - string
    - string
    - string
    - string
    - string
    - uint32_t
    - uint32_t
    - string
    - uint32_t
    - string
    vattr_id_to_vlabel_id:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 2
    - 2
    vlabel_id_to_local_vid_range:
    - - 0
      - 4
    - - 4294967295
      - 4294967295
    - - 4294967295
      - 4294967295
  - gid: 1
    max_global_vid: 9
    min_global_vid: 5
    num_incoming_edges: 5
    num_outgoing_edges: 5
    num_vertices: 5
    vattr_id_to_file_path:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ../attributes/1/cast_vid.bin
    - ../attributes/1/cast_name.bin
    - ../attributes/1/director_vid.bin
    - ../attributes/1/director_name.bin
    vattr_id_to_max_string_length:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 16
    - 0
    - 17
    vattr_id_to_vattr_type:
    - uint32_t
    - uint8_t
    - uint16_t
    - string
    - string
    - string
    - string
    - string
    - uint32_t
    - uint32_t
    - string
    - uint32_t
    - string
    vattr_id_to_vlabel_id:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 2
    - 2
    vlabel_id_to_local_vid_range:
    - - 4294967295
      - 4294967295
    - - 0
      - 2
    - - 3
      - 4
  vlabel_id_to_local_vid_range:
  - - 0
    - 4
  - - 5
    - 7
  - - 8
    - 9
