GraphMetadata:
  num_vertices: 8
  num_edges: 26
  max_vid: 7
  min_vid: 0
  count_border_vertices: 0
  num_subgraphs: 1
  subgraphs:
    - gid: 0
      num_vertices: 8
      num_incoming_edges: 26
      num_outgoing_edges: 26
      max_vid: 7
      min_vid: 0
