GraphMetadata:
  num_vertices: 8
  num_edges: 24
  max_vid: 7
  min_vid: 0
  count_border_vertices: 0
  num_subgraphs: 2
  subgraphs:
    - gid: 0
      num_vertices: 4
      num_incoming_edges: 12
      num_outgoing_edges: 12
      max_vid: 3
      min_vid: 0
    - gid: 1
      num_vertices: 4
      num_incoming_edges: 12
      num_outgoing_edges: 12
      max_vid: 7
      min_vid: 4
